-- Settings -> Staff accounts: a per-employee, admin-set toggle for the
-- Dashboard's "Priority & To-Do's" card (§2.79/2.80 -- daily_todo tickets
-- plus tickets at any priority tier flagged "Highlight in tasks"). That
-- card is shop-wide by default (everyone's, not just yours) -- this lets
-- an admin flip specific people over to seeing only the slice of it that's
-- actually assigned to them, same admin-sets-it-for-anyone shape as
-- excluded_from_chore_rotation (migration 033) and show_parts_on_dashboard
-- (migration 058) before it.
--
-- Defaults FALSE (shop-wide) for everyone -- opt-in to the narrower view,
-- not a change of behavior for anyone who hasn't been switched over.
ALTER TABLE employees ADD COLUMN dashboard_priority_personal_only BOOLEAN NOT NULL DEFAULT FALSE;
